# Generated by Django 2.2 on 2020-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ting_hiring_challenge_app', '0002_auto_20200227_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='player_address',
            field=models.TextField(blank=True, max_length=900),
        ),
    ]
